
const REPO_NAME                           = "StarsectorHTML";
const BASE_PATH                           = location.hostname === "127.0.0.1" ? "." : `/${REPO_NAME}`;
const CODEX_ICON_FOLDER_PATH              = `${BASE_PATH}/Resources/Images/Codex`
const { }                                 = "CODEX---------------------------------------";
const CODEX_ICON_ABILITIES                = `${CODEX_ICON_FOLDER_PATH}/abilities.png`
const CODEX_ICON_COMMODITIES              = `${CODEX_ICON_FOLDER_PATH}/commodities.png`
const CODEX_ICON_CUSTOM                   = `${CODEX_ICON_FOLDER_PATH}/custom.png`
const CODEX_ICON_FIGHTERS                 = `${CODEX_ICON_FOLDER_PATH}/fighters.png`
const CODEX_ICON_GALLERY                  = `${CODEX_ICON_FOLDER_PATH}/gallery.png`
const CODEX_ICON_GAME_MECHANICS           = `${CODEX_ICON_FOLDER_PATH}/game_mechanics.png`
const CODEX_ICON_HULLMODS                 = `${CODEX_ICON_FOLDER_PATH}/hullmods.png`
const CODEX_ICON_INDUSTRIES               = `${CODEX_ICON_FOLDER_PATH}/industries.png`
const CODEX_ICON_MANUAL_ARMOR             = `${CODEX_ICON_FOLDER_PATH}/manual_armor.png`
const CODEX_ICON_MANUAL_BALLISTIC_WEAPONS = `${CODEX_ICON_FOLDER_PATH}/manual_ballistic_weapons.png`
const CODEX_ICON_MANUAL_COMBAT            = `${CODEX_ICON_FOLDER_PATH}/manual_combat.png`
const CODEX_ICON_MANUAL_ENERGY_WEAPONS    = `${CODEX_ICON_FOLDER_PATH}/manual_energy_weapons.png`
const CODEX_ICON_MANUAL_FLUX              = `${CODEX_ICON_FOLDER_PATH}/manual_flux.png`
const CODEX_ICON_MANUAL_MISSILES          = `${CODEX_ICON_FOLDER_PATH}/manual_missiles.png`
const CODEX_ICON_MANUAL_OTHER             = `${CODEX_ICON_FOLDER_PATH}/manual_other.png`
const CODEX_ICON_MANUAL_SHIELDS           = `${CODEX_ICON_FOLDER_PATH}/manual_shields.png`
const CODEX_ICON_MANUAL_TRIPAD            = `${CODEX_ICON_FOLDER_PATH}/manual_tripad.png`
const CODEX_ICON_MANUAL_UI                = `${CODEX_ICON_FOLDER_PATH}/manual_ui.png`
const CODEX_ICON_MANUAL_UI2               = `${CODEX_ICON_FOLDER_PATH}/manual_ui2.png`
const CODEX_ICON_MANUAL_VENTING           = `${CODEX_ICON_FOLDER_PATH}/manual_venting.png`
const CODEX_ICON_MARKET_CONDITIONS        = `${CODEX_ICON_FOLDER_PATH}/market_conditions.png`
const CODEX_ICON_SHIPS                    = `${CODEX_ICON_FOLDER_PATH}/ships.png`
const CODEX_ICON_SHIP_SYSTEMS             = `${CODEX_ICON_FOLDER_PATH}/ship_systems.png`
const CODEX_ICON_SKILLS                   = `${CODEX_ICON_FOLDER_PATH}/skills.png`
const CODEX_ICON_SPACERS_MANUAL           = `${CODEX_ICON_FOLDER_PATH}/spacers_manual.png`
const CODEX_ICON_SPECIAL_ITEMS            = `${CODEX_ICON_FOLDER_PATH}/special_items.png`
const CODEX_ICON_STARS_PLANETS            = `${CODEX_ICON_FOLDER_PATH}/stars_planets.png`
const CODEX_ICON_STATIONS                 = `${CODEX_ICON_FOLDER_PATH}/stations.png`
const CODEX_ICON_WEAPONS                  = `${CODEX_ICON_FOLDER_PATH}/weapons.png`
const { }                                 = "ICONS--------------------------------------";
const ICON_FOLDER_PATH                    = `${BASE_PATH}/Resources/Images/Icons`
const ICON_ERROR_PATH                     = `${ICON_FOLDER_PATH}/alert.png`
const ICON_DOWNLOAD_PATH                  = `${ICON_FOLDER_PATH}/download.png`
const ICON_INFO_PATH                      = `${ICON_FOLDER_PATH}/info.png`
const ICON_CODEX_ARROW_UP                 = `${ICON_FOLDER_PATH}/arrow_up.png`
const { }                                 = "WEAPON-ICONS-------------------------------";
const ICON_DAMAGE_TYPE_ENERGY             = `${ICON_FOLDER_PATH}/damagetype_energy.png`
const ICON_DAMAGE_TYPE_FRAGMENTATION      = `${ICON_FOLDER_PATH}/damagetype_fragmentation.png`
const ICON_DAMAGE_TYPE_HIGH_EXPLOSIVE     = `${ICON_FOLDER_PATH}/damagetype_high_explosive.png`
const ICON_DAMAGE_TYPE_KINETIC            = `${ICON_FOLDER_PATH}/damagetype_kinetic.png`
const ICON_DAMAGE_TYPE_OTHER              = `${ICON_FOLDER_PATH}/damagetype_other.png`
